function setupKarten() {
    let thema

    thema = '9.1 Reelle Zahlen'
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{4}\\]', '\\(2\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{9}\\]', '\\(3\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{16}\\]', '\\(4\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{25}\\]', '\\(5\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{36}\\]', '\\(6\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{49}\\]', '\\(7\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{64}\\]', '\\(8\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{81}\\]', '\\(9\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{100}\\]', '\\(10\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{121}\\]', '\\(11\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{144}\\]', '\\(12\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{400}\\]', '\\(20\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{2500}\\]', '\\(50\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{360000}\\]', '\\(600\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{49000000}\\]', '\\(7000\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{\\frac{1}{4}}\\]', '\\(\\frac{1}{2}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{\\frac{1}{9}}\\]', '\\(\\frac{1}{3}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{\\frac{1}{16}}\\]', '\\(\\frac{1}{4}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{\\frac{1}{25}}\\]', '\\(\\frac{1}{5}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{\\frac{1}{36}}\\]', '\\(\\frac{1}{6}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{\\frac{1}{49}}\\]', '\\(\\frac{1}{7}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{\\frac{1}{64}}\\]', '\\(\\frac{1}{8}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{\\frac{1}{81}}\\]', '\\(\\frac{1}{9}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{\\frac{1}{100}}\\]', '\\(\\frac{1}{10}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{\\frac{1}{121}}\\]', '\\(\\frac{1}{11}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{\\frac{1}{144}}\\]', '\\(\\frac{1}{12}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{\\frac{4}{9}}\\]', '\\(\\frac{2}{3}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{\\frac{36}{25}}\\]', '\\(\\frac{6}{5}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{\\frac{16}{49}}\\]', '\\(\\frac{4}{7}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{\\frac{121}{144}}\\]', '\\(\\frac{11}{12}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{0,01}\\]', '\\(0,1\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{0,04}\\]', '\\(0,2\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{0,16}\\]', '\\(0,4\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{1,21}\\]', '\\(1,1\\)'))
    karten.push(new Karte(thema, 'Gib an, zwischen welchen aufeinanderfolgenden natürlichen Zahlen die Wurzel liegt. \\[\\sqrt{3}\\]', '\\(1<\\sqrt{3}<2\\)'))
    karten.push(new Karte(thema, 'Gib an, zwischen welchen aufeinanderfolgenden natürlichen Zahlen die Wurzel liegt. \\[\\sqrt{5}\\]', '\\(2<\\sqrt{5}<3\\)'))
    karten.push(new Karte(thema, 'Gib an, zwischen welchen aufeinanderfolgenden natürlichen Zahlen die Wurzel liegt. \\[\\sqrt{6}\\]', '\\(2<\\sqrt{6}<3\\)'))
    karten.push(new Karte(thema, 'Gib an, zwischen welchen aufeinanderfolgenden natürlichen Zahlen die Wurzel liegt. \\[\\sqrt{10}\\]', '\\(3<\\sqrt{10}<4\\)'))
    karten.push(new Karte(thema, 'Gib an, zwischen welchen aufeinanderfolgenden natürlichen Zahlen die Wurzel liegt. \\[\\sqrt{70}\\]', '\\(8<\\sqrt{70}<9\\)'))
    karten.push(new Karte(thema, 'Gib an, zwischen welchen aufeinanderfolgenden natürlichen Zahlen die Wurzel liegt. \\[\\sqrt{\\frac{2}{3}}\\]', '\\(0<\\sqrt{\\frac{2}{3}}<1\\)'))
    karten.push(new Karte(thema, 'Bestimme, ob es sich um eine rationale oder irrationle Zahl handelt. \\[\\sqrt{4}\\]', 'rational'))
    karten.push(new Karte(thema, 'Bestimme, ob es sich um eine rationale oder irrationle Zahl handelt. \\[\\sqrt{9}\\]', 'rational'))
    karten.push(new Karte(thema, 'Bestimme, ob es sich um eine rationale oder irrationle Zahl handelt. \\[\\sqrt{0,36}\\]', 'rational'))
    karten.push(new Karte(thema, 'Bestimme, ob es sich um eine rationale oder irrationle Zahl handelt. \\[\\sqrt{\\frac{16}{25}}\\]', 'rational'))
    karten.push(new Karte(thema, 'Bestimme, ob es sich um eine rationale oder irrationle Zahl handelt. \\[\\frac{5}{7}\\]', 'rational'))
    karten.push(new Karte(thema, 'Bestimme, ob es sich um eine rationale oder irrationle Zahl handelt. \\[1,5367\\]', 'rational'))
    karten.push(new Karte(thema, 'Bestimme, ob es sich um eine rationale oder irrationle Zahl handelt. \\[\\sqrt{5}\\]', 'irrational'))
    karten.push(new Karte(thema, 'Bestimme, ob es sich um eine rationale oder irrationle Zahl handelt. \\[\\sqrt{\\frac{3}{4}}\\]', 'irrational'))
    karten.push(new Karte(thema, 'Bestimme, ob es sich um eine rationale oder irrationle Zahl handelt. \\[\\sqrt{1,43}\\]', 'irrational'))
    karten.push(new Karte(thema, 'Bestimme, ob es sich um eine rationale oder irrationle Zahl handelt. \\[\\sqrt{10}\\]', 'irrational'))
    karten.push(new Karte(thema, 'Berechne mithilfe der Wurzelgesetze. \\[\\sqrt{2}\\cdot\\sqrt{8}\\]', '\\(4\\)'))
    karten.push(new Karte(thema, 'Berechne mithilfe der Wurzelgesetze. \\[\\sqrt{3}\\cdot\\sqrt{12}\\]', '\\(6\\)'))
    karten.push(new Karte(thema, 'Berechne mithilfe der Wurzelgesetze. \\[\\sqrt{0,1}\\cdot\\sqrt{40}\\]', '\\(2\\)'))
    karten.push(new Karte(thema, 'Berechne mithilfe der Wurzelgesetze. \\[\\sqrt{2,5}\\cdot\\sqrt{10}\\]', '\\(5\\)'))
    karten.push(new Karte(thema, 'Berechne mithilfe der Wurzelgesetze. \\[\\sqrt{81\\cdot49}\\]', '\\(63\\)'))
    karten.push(new Karte(thema, 'Berechne mithilfe der Wurzelgesetze. \\[\\sqrt{36\\cdot64}\\]', '\\(48\\)'))
    karten.push(new Karte(thema, 'Berechne mithilfe der Wurzelgesetze. \\[\\sqrt{72}\\div\\sqrt{2}\\]', '\\(6\\)'))
    karten.push(new Karte(thema, 'Berechne mithilfe der Wurzelgesetze. \\[\\sqrt{50}\\div\\sqrt{2}\\]', '\\(5\\)'))
    karten.push(new Karte(thema, 'Berechne mithilfe der Wurzelgesetze. \\[\\sqrt{75}\\div\\sqrt{3}\\]', '\\(5\\)'))
    karten.push(new Karte(thema, 'Berechne mithilfe der Wurzelgesetze. \\[\\sqrt{500}\\div\\sqrt{5}\\]', '\\(10\\)'))
    karten.push(new Karte(thema, 'Berechne mithilfe der Wurzelgesetze. \\[\\frac{\\sqrt{12}}{\\sqrt{48}}\\]', '\\(\\frac{1}{2}\\)'))
    karten.push(new Karte(thema, 'Berechne mithilfe der Wurzelgesetze. \\[\\frac{\\sqrt{3}}{\\sqrt{27}}\\]', '\\(\\frac{1}{3}\\)'))
    karten.push(new Karte(thema, 'Berechne mithilfe der Wurzelgesetze. \\[\\frac{\\sqrt{8}}{\\sqrt{18}}\\]', '\\(\\frac{2}{3}\\)'))
    karten.push(new Karte(thema, 'Berechne mithilfe der Wurzelgesetze. \\[\\frac{\\sqrt{1440}}{\\sqrt{10}}\\]', '\\(12\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{7^2}\\]', '\\(7\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{123^2}\\]', '\\(123\\)'))
    karten.push(new Karte(thema, 'Bestimme die Quadratwurzel im Kopf. \\[\\sqrt{0,53^2}\\]', '\\(0,53\\)'))

    thema = '10.1 Daten & Wahrscheinlichkeit'
    karten.push(new Karte(thema, 'Prüfe, ob die beiden Ereignisse A und B stochastisch unabhängig sind. \\begin{array} {|r|r|}\\hline  & A & \\overline{A} & Summe \\\\ \\hline B & 0,3 & 0,4 & 0,7 \\\\ \\hline \\overline{B} & 0,1 & 0,2 & 0,3 \\\\ \\hline Summe & 0,4 & 0,6 & 1 \\\\ \\hline  \\end{array}', 'Hier gilt \\(P(A)\\cdot P(B)\\neq P(A\\cap B)\\), also sind die Ereignisse abhängig.'))
    karten.push(new Karte(thema, 'Prüfe, ob die beiden Ereignisse A und B stochastisch unabhängig sind. \\begin{array} {|r|r|}\\hline  & A & \\overline{A} & Summe \\\\ \\hline B & 0,1 & 0,15 & 0,25 \\\\ \\hline \\overline{B} & 0,3 & 0,45 & 0,75 \\\\ \\hline Summe & 0,4 & 0,6 & 1 \\\\ \\hline  \\end{array}', 'Hier gilt \\(P(A)\\cdot P(B) = P(A\\cap B)\\), also sind die Ereignisse unabhängig.'))
    karten.push(new Karte(thema, 'Berechne \\(P_A(B)\\). \\begin{array} {|r|r|}\\hline  & A & \\overline{A} & Summe \\\\ \\hline B & 0,2 & 0,4 & 0,6 \\\\ \\hline \\overline{B} & 0,3 & 0,1 & 0,4 \\\\ \\hline Summe & 0,5 & 0,5 & 1 \\\\ \\hline  \\end{array}', '\\(P_A(B) = \\frac{P(A \\cap B)}{P(A)} = \\frac{0,2}{0,5} = 0,4\\)'))
    karten.push(new Karte(thema, 'Erstelle die zugehörige Vierfeldertafel. \\[P(A)=0,5\\] \\[P(\\overline{B})=0,7\\] \\[P(\\overline{A} \\cap B) = 0,1\\]', '\\begin{array} {|r|r|}\\hline  & A & \\overline{A} & Summe \\\\ \\hline B & 0,2 & 0,1 & 0,3 \\\\ \\hline \\overline{B} & 0,3 & 0,4 & 0,7 \\\\ \\hline Summe & 0,5 & 0,5 & 1 \\\\ \\hline  \\end{array}'))

    thema = '10.2 quadratische Funktionen & Gleichungen'
    karten.push(new Karte(thema, 'Forme die Gleichung in die Normalform um. \\[(x-5) \\cdot (x+5) = 0\\]', '\\(x^2-25=0\\)'))
    karten.push(new Karte(thema, 'Forme die Gleichung in die Normalform um. \\[(x-3) \\cdot (x-5) = 0\\]', '\\(x^2-8x+15=0\\)'))
    karten.push(new Karte(thema, 'Forme die Gleichung in die Normalform um. \\[(x-1) \\cdot (x+2) = 0\\]', '\\(x^2+x-2=0\\)'))
    karten.push(new Karte(thema, 'Forme die Gleichung in die Normalform um. \\[(x-3) \\cdot (x+2) = 0\\]', '\\(x^2-x-6=0\\)'))
    karten.push(new Karte(thema, 'Forme die Gleichung in die Normalform um. \\[(x-2) \\cdot (x+8) = 0\\]', '\\(x^2+6x-16=0\\)'))
    karten.push(new Karte(thema, 'Forme die Funktion in die Normalform um. \\[f(x) = 5 \\cdot (x+2) \\cdot (x+5)\\]', '\\(f(x)=5x^2+35x+50\\)'))
    karten.push(new Karte(thema, 'Forme die Funktion in die Normalform um. \\[f(x) = 2 \\cdot (x+1) \\cdot (x+3)\\]', '\\(f(x)=2x^2+8x+6\\)'))
    karten.push(new Karte(thema, 'Forme die Gleichung in die faktorisierte Form um. \\[3x^2+6x-45=0\\]', '\\[3 \\cdot (x+5) \\cdot (x-3)\\]'))
    karten.push(new Karte(thema, 'Forme die Gleichung in die faktorisierte Form um. \\[x^2-2x+1=0\\]', '\\[(x-1) \\cdot (x-1) = (x-1)^2 = 0\\]'))
    karten.push(new Karte(thema, 'Forme die Funktion in die faktorisierte Form um. \\[f(x)=(x-1)^2+4\\]', '\\[f(x)=(x+1)\\cdot(x-3)\\]'))
    karten.push(new Karte(thema, 'Gib eine Gleichung in der Form \\(x^2+px+q=0\\) mit der Lösungsmenge \\(L=\\{7;9\\}\\) an.', '\\(x^2-16x+63=0\\)'))
    karten.push(new Karte(thema, 'Gib eine Gleichung in der Form \\(x^2+px+q=0\\) mit der Lösungsmenge \\(L=\\{5;6\\}\\) an.', '\\(x^2-11x+30=0\\)'))
    karten.push(new Karte(thema, 'Gib eine Gleichung in der Form \\(x^2+px+q=0\\) mit der Lösungsmenge \\(L=\\{-8;-3\\}\\) an.', '\\(x^2+11x+24=0\\)'))
    karten.push(new Karte(thema, 'Gib eine Gleichung in der Normalform mit der Lösungsmenge \\(L=\\{-2;2\\}\\) an.', '\\(x^2-4=0\\)'))
    karten.push(new Karte(thema, 'Gib eine Gleichung in der Normalform mit der Lösungsmenge \\(L=\\{0;5\\}\\) an.', '\\(x^2-5x=0\\)'))
    karten.push(new Karte(thema, 'Gib eine Gleichung in der Normalform mit der Lösungsmenge \\(L=\\{-2;0\\}\\) an.', '\\(x^2+2x=0\\)'))
    karten.push(new Karte(thema, 'Gib eine Gleichung in der faktorisierten Form mit der Lösungsmenge \\(L=\\{-3;1\\}\\) an.', '\\((x+3)\\cdot(x-1)=0\\)'))
    karten.push(new Karte(thema, 'Gib eine quadratische Gleichung in der faktorisierten Form mit der Lösungsmenge \\(L=\\{4\\}\\) an.', '\\((x-4)^2=0\\)'))
    karten.push(new Karte(thema, 'Zerlege in Linearfaktoren und bestimme die Lösungsmenge. \\[2x^2-18x+28=0\\]', '\\(L=\\{2;7\\}\\)'))
    karten.push(new Karte(thema, 'Zerlege in Linearfaktoren und bestimme die Lösungsmenge. \\[\\frac{1}{2}x^2+3x+4=0\\]', '\\(L=\\{-4;-2\\}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Lösungsmenge. \\[x^2-6x=0\\]', '\\(L=\\{0;6\\}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Lösungsmenge. \\[x^2-9=0\\]', '\\(L=\\{-3;3\\}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Lösungsmenge. \\[x^2=-3x\\]', '\\(L=\\{-3;0\\}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Lösungsmenge. \\[x^2=49\\]', '\\(L=\\{-7;7\\}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Lösungsmenge. \\[2x^2=-8x\\]', '\\(L=\\{-4;0\\}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Lösungsmenge. \\[3x^2=48\\]', '\\(L=\\{-4;4\\}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Lösungsmenge. \\[3x^2=-6\\]', '\\(L=\\{\\}\\)'))
    karten.push(new Karte(thema, 'Bestimme die Lösungsmenge. \\[4x^2+5x=3x^2\\]', '\\(L=\\{-5;0\\}\\)'))
}